#namespace
namespace: ajay-ns

#deployment
replicas: 4
deployment:
  labels: 
    app: school-web
  name: school-web
image:
  repository: ajaykumar5292/school-web
  tag: v1.0.1
port: 80


#service
service:
  app: school-web
  port: 80
  type: LoadBalancer
  