apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: school-web-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://ajay001-ai.github.io/school-web-app
    chart: school-web
    targetRevision: "*" 
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: ajay-ns 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 