apiVersion: apps/v1
kind: Deployment
metadata:
  name: school-web-deployment
  namespace: ajay-ns
spec:
  replicas: 4
  selector:
    matchLabels: 
      app: school-web
  template:
    metadata:
      labels:
        app: school-web
    spec: 
      - containers:
          name: school-web-container
          image: ajaykumar5292/school:v1.0.1
          ports:
            - containerPort: 80
             