apiVersion: v1
kind: Service
metadata:
  name: school-web-service
  namespace: ajay-ns
spec:
  selector:
    app: school-web
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  